### ISSUE TITLE
A SyntaxError when run "mme-server quickstart"

### ISSUE THREAD

**Issue by deb0612** [MatchmakerExchange/reference-server#12]
Dear sir,
It appear something wrong when running mme-server quickstart.
here is the massage

--------------------------------------------------------------------------------------------------

```
Traceback (most recent call last):
  File "/home/debbie/demo/reference-server/.virtualenv/bin/mme-server", line 11, in <module>
    load_entry_point('mme-server', 'console_scripts', 'mme-server')()
  File "/home/debbie/demo/reference-server/.virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/debbie/demo/reference-server/.virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/debbie/demo/reference-server/.virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/debbie/demo/reference-server/.virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/debbie/demo/reference-server/mme_server/__init__.py", line 1, in <module>
    from .cli import main
  File "/home/debbie/demo/reference-server/mme_server/cli.py", line 13, in <module>
    from .backend import get_backend
  File "/home/debbie/demo/reference-server/mme_server/backend.py", line 12, in <module>
    from .managers import Managers
  File "/home/debbie/demo/reference-server/mme_server/managers/__init__.py", line 10, in <module>
    from .vocabularies import VocabularyManager
  File "/home/debbie/demo/reference-server/mme_server/managers/vocabularies/__init__.py", line 12, in <module>
    from .parsers import OBOParser, GeneParser
  File "/home/debbie/demo/reference-server/mme_server/managers/vocabularies/parsers.py", line 145
    retrn TSVParser._documents(self, columns)
                  ^
SyntaxError: invalid syntax
```

-----------------------------------------------------------------------------

**Comment by deb0612** [comment]
I had found a spell error in the last line "retrn". When I correct this "return",there is another error shown.

---------------------------------------------------------------------------------------
```
Traceback (most recent call last):
  File "/home/debbie/demo/reference-server/.virtualenv/bin/mme-server", line 11, in <module>
    load_entry_point('mme-server', 'console_scripts', 'mme-server')()
  File "/home/debbie/demo/reference-server/mme_server/cli.py", line 221, in main
    function(**kwargs)
  File "/home/debbie/demo/reference-server/mme_server/cli.py", line 50, in quickstart
    index_file('hpo', hpo_filename, hpo_url)
  File "/home/debbie/demo/reference-server/mme_server/cli.py", line 68, in index_file
    index_funcs[index](filename=filename)
  File "/home/debbie/demo/reference-server/mme_server/managers/vocabularies/__init__.py", line 101, in index_hpo
    return self.index_file(doc_type=doc_type, filename=filename, Parser=OBOParser)
  File "/home/debbie/demo/reference-server/mme_server/managers/vocabularies/__init__.py", line 97, in index_file
    for batch in self.iter_batches(parser, batch_size=batch_size):
  File "/home/debbie/demo/reference-server/mme_server/managers/vocabularies/__init__.py", line 78, in iter_batches
    for item in iterator:
  File "/home/debbie/demo/reference-server/mme_server/managers/vocabularies/parsers.py", line 28, in documents
    parser = BaseOBOParser(codecs.open(self._filename, encoding='utf-8'))
  File "/home/debbie/demo/reference-server/mme_server/managers/vocabularies/obo.py", line 148, in __init__
    self._read_headers()
  File "/home/debbie/demo/reference-server/mme_server/managers/vocabularies/obo.py", line 237, in _read_headers
    key, value = self._parse_line(line)
  File "/home/debbie/demo/reference-server/mme_server/managers/vocabularies/obo.py", line 227, in _parse_line
    value = Value(value, mod)
  File "/home/debbie/demo/reference-server/mme_server/managers/vocabularies/obo.py", line 60, in __init__
    self.value = str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 52: ordinal not in range(128)
```

---------------------------------------------------------------------------------------
