### ISSUE TITLE
benchmark_patients.json not found

### ISSUE THREAD

**Issue by northwestwitch** [MatchmakerExchange/reference-server#9]
Hi! I'm trying to set up a mme server for my institution and this reference-server looks like a good starting point!
While following the instructions I get stuck at the command
``mme-server quickstart`` 

where I get this error message:

INFO:mme_server.cli:Downloading file from: https://raw.githubusercontent.com/ga4gh/mme-apis/hotfix/v1.0b/testing/benchmark_patients.json
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py36/bin/mme-server", line 11, in <module>
    load_entry_point('mme-server', 'console_scripts', 'mme-server')()
  File "/Users/chiararasi/Documents/work/GITs/reference-server/mme_server/cli.py", line 221, in main
    function(**kwargs)
  File "/Users/chiararasi/Documents/work/GITs/reference-server/mme_server/cli.py", line 53, in quickstart
    index_file('patients', data_filename, data_url)
  File "/Users/chiararasi/Documents/work/GITs/reference-server/mme_server/cli.py", line 57, in index_file
    fetch_resource(filename, url)
  File "/Users/chiararasi/Documents/work/GITs/reference-server/mme_server/cli.py", line 76, in fetch_resource
    urlretrieve(url, filename)
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/chiararasi/miniconda3/envs/py36/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Could it be that benchmark_patients.json was removed or renamed?

Thanks in advance! 
Chiara

**Comment by northwestwitch** [comment]
If you modify the cli to download the patient data from "https://raw.githubusercontent.com/ga4gh/mme-apis/master/testing/benchmark_patients.json" it works!

**Comment by northwestwitch** [comment]
Another update: if you use the above benchmark_patients.json file, one of the tests fail. Specifically there is an assertion error in **test_fuzzy_search** occurring with the code: 
``self.assertEqual(hits[0]['_id'], 'P0001059')``

Full error message:
``
Traceback (most recent call last):
  File "/Users/chiararasi/Documents/work/GITs/reference-server/mme_server/tests/test_app.py", line 133, in test_fuzzy_search
    self.assertEqual(hits[0]['_id'], 'P0001059')
AssertionError: 'P0001058' != 'P0001059'
- P0001058
?        ^
+ P0001059
?        ^
``

**Comment by Relequestual** [comment]
This may be due to not using a specific version of HPO for the tests.
Unfortunatly, I don't know if this reference server is maintained or not. Will wait to hear back from @buske

**Comment by buske** [comment]
Hi @northwestwitch, thank you so much for the feedback and sorry for this issues you've run into. Yes, it looks like this source file has moved, but the one you're using might be a slightly different version. I'll take a look and update the tests and file url accordingly. Thanks for pointing this out!

**Comment by northwestwitch** [comment]
You're welcome! :)

**Comment by buske** [comment]
Fixed by #11
